In [1]:
import sqlalchemy as sql

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
conn_cadri = sql.create_engine('postgresql://postgres:%24h%5B6%3B%3AsqyA4%25f6nL%5Bg@postgres.driva.io:5432/cadri')

In [3]:
df_cadri = pd.read_sql(sql.text('SELECT * FROM cadri.cadri_e_pareceres_com_residuos'), con=conn_cadri.connect())
df_cadri.head()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_descricao_da_atividade,destinacao_bacia_hidrografica,destinacao_nlic_cert_funcion,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao
0,1,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.06 t / ano,BORRA DE TRATAMENTO TERMICO,ABNT NBR 1004:2003,CARACTERIZADO,...,Resíduos contaminados; tratamento e disposição de,2 - TIETÊ ALTO ZONA METROPOLITANA,32008615.0,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.06,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN
1,2,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.5 t / ano,BORRA DE TRATAMENTO TERMICO,ABNT NBR 1004:2003,CARACTERIZADO,...,Resíduos contaminados; tratamento e disposição de,2 - TIETÊ ALTO ZONA METROPOLITANA,32008615.0,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.50,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN
2,3,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.01 t / ano,LAMPADAS INTEIRAS,ABNT NBR 1004:2003,CARACTERIZADO,...,Resíduos contaminados; tratamento e disposição de,2 - TIETÊ ALTO ZONA METROPOLITANA,32008615.0,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.01,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN
3,4,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.01 t / ano,LAMPADAS INTEIRAS,ABNT NBR 1004:2003,CARACTERIZADO,...,Resíduos contaminados; tratamento e disposição de,2 - TIETÊ ALTO ZONA METROPOLITANA,32008615.0,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.01,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN
4,1,D099,Outros resíduos perigosos - especificar Origem...,I,LIQUIDO,I/O,100 t / ano,"Conforme Boletim de Análise nº 10607/2014-1.1,...","Conforme Boletim de Análise nº 10607/2014-1.1,...",Característicos.,...,"Impermebializantes, solventes e produtos afins...",13 - JUNDIAÍ,36007875.0,2014-10-23 00:00:00,NaN,NaN,1.936786e+13,100.00,https://autenticidade.cetesb.sp.gov.br/pdf/121...,NaN

In [4]:
df_cadri.shape

(282697, 48)

In [5]:
def parse_unidade_medida(texto: str) -> str:
    if texto is None:
        return None
    
    texto = texto.split()
    texto = ''.join(texto[1:])
    return texto.strip()

df_cadri['unidade_medida'] = df_cadri['residuo_quantidade'].apply(parse_unidade_medida)

In [6]:
df_cadri.groupby('unidade_medida').count()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_descricao_da_atividade,destinacao_bacia_hidrografica,destinacao_nlic_cert_funcion,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao
unidade_medida,,,,,,,,,,,,,,,,,,,,,
,276,276,276,276,276,276,276,276,276,276,...,276,276,254,276,276,218,261,276,276,0
L/ano,3381,3381,3378,3381,3381,3378,3381,3319,3286,3304,...,3381,3273,2889,2890,30,2943,3088,3381,3381,0
Un/ano,8880,8880,8870,8880,8880,8870,8880,8492,8451,8446,...,8880,8426,7588,7588,7,8087,7564,8880,8880,0
kg/ano,54428,54428,54411,54428,54428,54424,54428,53797,53291,52848,...,54428,52468,47100,48603,12075,40120,50685,54428,54426,0
m3,41,41,41,41,41,41,41,41,41,41,...,41,41,30,30,0,35,34,41,41,0
m3/ano,4208,4208,4207,4208,4208,4207,4208,4184,4145,4130,...,4208,4142,3147,3150,74,3775,3132,4208,4208,0
t/ano,207791,207791,207706,207791,207791,207729,207791,205021,203051,201611,...,207791,198349,188549,190974,36194,167258,192030,207791,207790,1

In [7]:
df_cadri[df_cadri['unidade_medida'].isin(['m3/ano'])].head()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_bacia_hidrografica,destinacao_nlic_cert_funcion,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao,unidade_medida
173,1,A099,Efluente proveniente dos lavadores de gases - ...,IIA,LIQUIDO,I/O,150 m3 / ano,Conforme laudo apresentado à CETESB,Standards methods for the examination of water...,Caracteristicos,...,73 - MOGI-GUAÇÚ,43003557.0,2010-01-22 00:00:00,NaN,4.473467e+13,8.700115e+12,150.0,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN,m3/ano
175,1,A099,Lodo líquido de fossa séptica,IIA,LIQUIDO,I/O,16 m3 / ano,Lodo líquido de fossa séptica,Relatório de ensaio nº 22206/2012-2.1 da Opersan,Característicos,...,13 - JUNDIAÍ,36005581.0,2011-12-30 00:00:00,NaN,5.379390e+13,7.234499e+12,16.0,https://autenticidade.cetesb.sp.gov.br/pdf/120...,NaN,m3/ano
176,2,D099,Efluente industrial contendo cromo hexavalente,I,LIQUIDO,I/O,500 m3 / ano,Efluente industrial contendo cromo hexavalente,Relatório de ensaio nº 22210/2012-2.1 da OPERSAN,Característicos,...,13 - JUNDIAÍ,36005581.0,2011-12-30 00:00:00,NaN,5.379390e+13,7.234499e+12,500.0,https://autenticidade.cetesb.sp.gov.br/pdf/120...,NaN,m3/ano
177,3,D099,Efluente industrial gerado na fabricação de pi...,I,LIQUIDO,I/O,500 m3 / ano,Efluente industrial gerado na fabricação de pi...,Relatório de ensaio nº 22211/2012-2.1 da OPERSAN,Característicos,...,13 - JUNDIAÍ,36005581.0,2011-12-30 00:00:00,NaN,5.379390e+13,7.234499e+12,500.0,https://autenticidade.cetesb.sp.gov.br/pdf/120...,NaN,m3/ano
333,1,A099,Lodo de fossa séptica,IIA,PASTOSO,O,48 m3 / ano,Lodo de fossa séptica,Visual,Característicos,...,1 - TIETÊ ALTO CABECEIRAS,32005442.0,2010-11-30 00:00:00,NaN,NaN,NaN,48.0,https://autenticidade.cetesb.sp.gov.br/pdf/123...,NaN,m3/ano

In [8]:
df_cadri[df_cadri['unidade_medida'].isin(['m3'])].head()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_bacia_hidrografica,destinacao_nlic_cert_funcion,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao,unidade_medida
5839,9,D099,RESÍDUOS DE FIXADOR E BRANQUEADOR USADOS,I,LIQUIDO,I,3 m3,"Tiosulfato de amonia, ácido acetico, prata e água",Bibliografia,Líquido ambar com odor de amônia,...,1 - TIETÊ ALTO CABECEIRAS,26003247.0,2011-09-20 00:00:00,NaN,1.829851e+12,6.125276e+12,3.0,https://autenticidade.cetesb.sp.gov.br/pdf/121...,NaN,m3
5840,10,D099,RESÍDUOS DE TINTA COM SOLVENTES DE ORIGEM INDU...,I,PASTOSO,I/O,2 m3,Borra de tintas,Visual,Característico,...,1 - TIETÊ ALTO CABECEIRAS,26003247.0,2011-09-20 00:00:00,NaN,1.829851e+12,6.125276e+12,2.0,https://autenticidade.cetesb.sp.gov.br/pdf/121...,NaN,m3
20832,1,A009,Eucatex - forro madeirite (estoque passivo).,IIA,SOLIDO,O,200 m3,Madeira.,Visual.,Característicos.,...,61 - PARAÍBA,57000588.0,2011-05-25 00:00:00,NaN,7.689002e+12,7.288008e+12,200.0,https://autenticidade.cetesb.sp.gov.br/pdf/125...,NaN,m3
21816,1,D099,Água subterrânea proveniente de remediação do ...,I,LIQUIDO,I/O,350 m3,Ver Boletins de Análise nº 81219/2012-0; 25928...,Standard Methods,"Cor, odor e aspecto característicos",...,51 - BAIXADA SANTISTA,NaN,None,NaN,5.197936e+13,4.377652e+13,350.0,https://autenticidade.cetesb.sp.gov.br/pdf/121...,NaN,m3
27874,1,D099,Água contaminada com óleo (PASSIVO),I,LIQUIDO,O,35 m3,90 % Água / 10 % Óleo.,Bibliografia,Característicos,...,2 - TIETÊ ALTO ZONA METROPOLITANA,32005830.0,2011-08-27 00:00:00,NaN,7.183268e+13,7.234499e+12,35.0,https://autenticidade.cetesb.sp.gov.br/pdf/124...,NaN,m3

In [9]:
df_cadri['unidade_medida'] = df_cadri['unidade_medida'].map({
    'm3': 'm3/ano',
    'm3/ano': 'm3/ano',
    'kg/ano': 'kg/ano',
    'L/ano': 'L/ano',
    't/ano': 'ton/ano'
})

In [10]:
df_cadri.groupby('unidade_medida').count()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_descricao_da_atividade,destinacao_bacia_hidrografica,destinacao_nlic_cert_funcion,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao
unidade_medida,,,,,,,,,,,,,,,,,,,,,
L/ano,3381,3381,3378,3381,3381,3378,3381,3319,3286,3304,...,3381,3273,2889,2890,30,2943,3088,3381,3381,0
kg/ano,54428,54428,54411,54428,54428,54424,54428,53797,53291,52848,...,54428,52468,47100,48603,12075,40120,50685,54428,54426,0
m3/ano,4249,4249,4248,4249,4249,4248,4249,4225,4186,4171,...,4249,4183,3177,3180,74,3810,3166,4249,4249,0
ton/ano,207791,207791,207706,207791,207791,207729,207791,205021,203051,201611,...,207791,198349,188549,190974,36194,167258,192030,207791,207790,1

In [11]:
df_cadri['data'] = df_cadri['cadri_data'].apply(lambda date: pd.to_datetime(date, dayfirst=True))

In [12]:
df_cadri[['data', 'cadri_data']].head()

        data  cadri_data
0 2019-09-23  23/09/2019
1 2019-09-23  23/09/2019
2 2019-09-23  23/09/2019
3 2019-09-23  23/09/2019
4 2016-06-16  16/06/2016

In [13]:
df_cadri['ano'] = df_cadri['data'].dt.year
df_cadri['ano']

0         2019.0
1         2019.0
2         2019.0
3         2019.0
4         2016.0
           ...
282692    2014.0
282693    2010.0
282694    2016.0
282695    2016.0
282696    2016.0
Name: ano, Length: 282697, dtype: float64

In [14]:
df_cadri_filtrado = df_cadri[df_cadri['unidade_medida'].isin(['ton/ano', 'm3/ano', 'kg/ano', 'L/ano'])].copy()
df_cadri_filtrado.head()

,residuo_ordem_no_cadri,residuo_codigo,residuo_descricao,residuo_classe,residuo_estado_fisico,residuo_o_i,residuo_quantidade,residuo_composicao_aproximada,residuo_metodo_utilizado,residuo_cor_cheiro_aspecto,...,destinacao_data_lic_certific,is_parecer,geradora_cnpj,destinacao_cnpj,ton | m3 - ano,cadri_link,geradora_regiao,unidade_medida,data,ano
0,1,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.06 t / ano,BORRA DE TRATAMENTO TERMICO,ABNT NBR 1004:2003,CARACTERIZADO,...,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.06,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN,ton/ano,2019-09-23,2019.0
1,2,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.5 t / ano,BORRA DE TRATAMENTO TERMICO,ABNT NBR 1004:2003,CARACTERIZADO,...,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.50,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN,ton/ano,2019-09-23,2019.0
2,3,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.01 t / ano,LAMPADAS INTEIRAS,ABNT NBR 1004:2003,CARACTERIZADO,...,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.01,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN,ton/ano,2019-09-23,2019.0
3,4,D099,Outros resíduos perigosos - especificar Origem...,I,SOLIDO,I/O,0.01 t / ano,LAMPADAS INTEIRAS,ABNT NBR 1004:2003,CARACTERIZADO,...,2016-12-26 00:00:00,NaN,5.699210e+13,5.124428e+12,0.01,https://autenticidade.cetesb.sp.gov.br/pdf/126...,NaN,ton/ano,2019-09-23,2019.0
4,1,D099,Outros resíduos perigosos - especificar Origem...,I,LIQUIDO,I/O,100 t / ano,"Conforme Boletim de Análise nº 10607/2014-1.1,...","Conforme Boletim de Análise nº 10607/2014-1.1,...",Característicos.,...,2014-10-23 00:00:00,NaN,NaN,1.936786e+13,100.00,https://autenticidade.cetesb.sp.gov.br/pdf/121...,NaN,ton/ano,2016-06-16,2016.0

In [15]:
df_cadri_filtrado.shape

(269849, 51)

In [16]:
def padronizar_quantidade(linha):
    if linha['residuo_quantidade'] is None:
        return None

    residuo_quantidade = linha['residuo_quantidade'].split()[0]
    residuo_quantidade = float(residuo_quantidade)

    if linha['unidade_medida'] in ['ton/ano', 'm3/ano']:
        return residuo_quantidade
    elif linha['unidade_medida'] in ['kg/ano', 'L/ano']:
        return residuo_quantidade / 1000.0
    
    return None

def padronizar_unidade(unidade_medida):
    if unidade_medida in ['ton/ano', 'm3/ano']:
        return unidade_medida
    elif unidade_medida == 'kg/ano':
        return 'ton/ano'
    elif unidade_medida == 'L/ano':
        return 'm3/ano'

    return None

In [17]:
df_cadri_filtrado['qtde_padronizada'] = df_cadri_filtrado.apply(padronizar_quantidade, axis=1)
df_cadri_filtrado['unidade_padronizada'] = df_cadri_filtrado['unidade_medida'].apply(padronizar_unidade)

In [18]:
df_cadri_filtrado[['qtde_padronizada', 'unidade_padronizada']].count()

qtde_padronizada       269849
unidade_padronizada    269849
dtype: int64

In [19]:
df_cadri_filtrado[['qtde_padronizada', 'unidade_padronizada']].head()

   qtde_padronizada unidade_padronizada
0              0.06             ton/ano
1              0.50             ton/ano
2              0.01             ton/ano
3              0.01             ton/ano
4            100.00             ton/ano

In [20]:
df_cadri_filtrado['tipo_unidade_padronizada'] = df_cadri_filtrado['unidade_padronizada'].map({'ton/ano': 'massa', 'm3/ano': 'volume'})
df_cadri_filtrado[['unidade_padronizada', 'tipo_unidade_padronizada']].head()

  unidade_padronizada tipo_unidade_padronizada
0             ton/ano                    massa
1             ton/ano                    massa
2             ton/ano                    massa
3             ton/ano                    massa
4             ton/ano                    massa

In [21]:
df_cadri_filtrado = df_cadri_filtrado.rename(columns={'geradora_cnpj': 'cnpj'})
df_cadri_final = df_cadri_filtrado[['cnpj', 'qtde_padronizada', 'unidade_padronizada', 'tipo_unidade_padronizada', 'ano']].copy()
df_cadri_final.head()

,cnpj,qtde_padronizada,unidade_padronizada,tipo_unidade_padronizada,ano
0,5.699210e+13,0.06,ton/ano,massa,2019.0
1,5.699210e+13,0.50,ton/ano,massa,2019.0
2,5.699210e+13,0.01,ton/ano,massa,2019.0
3,5.699210e+13,0.01,ton/ano,massa,2019.0
4,NaN,100.00,ton/ano,massa,2016.0

In [22]:
df_cadri_final_agg = df_cadri_final.groupby(['cnpj', 'ano', 'tipo_unidade_padronizada', 'unidade_padronizada']).sum().reset_index()
df_cadri_final_agg.head()

,cnpj,ano,tipo_unidade_padronizada,unidade_padronizada,qtde_padronizada
0,5.839444e+07,2013.0,massa,ton/ano,0.06
1,1.221000e+09,2013.0,massa,ton/ano,200.00
2,1.904000e+09,2017.0,massa,ton/ano,65.00
3,1.904000e+09,2018.0,massa,ton/ano,200.00
4,1.904000e+09,2020.0,massa,ton/ano,200.00

In [25]:
def categorizar_faixa_massa_residuo(y: float):
    limites = [
        (0, 1000),
        (1000, 5000),
        (5000,10000),
        (10000,20000),
        (20000,40000),
        (40000,80000),
        (80000,160000),
        (160000,320000),
        (320000,640000),
        (640000,float('inf')),
    ]
    
    for i, limite in enumerate(limites):
        lim_inferior, lim_superior = limite
        if lim_inferior < y < lim_superior:
            return i
    return -1

In [26]:
df_cadri_final_agg['faixa_massa_residuo'] = df_cadri_final_agg['qtde_padronizada'].apply(categorizar_faixa_massa_residuo)
df_cadri_final_agg.head()

,cnpj,ano,tipo_unidade_padronizada,unidade_padronizada,qtde_padronizada,faixa_massa_residuo
0,5.839444e+07,2013.0,massa,ton/ano,0.06,0
1,1.221000e+09,2013.0,massa,ton/ano,200.00,0
2,1.904000e+09,2017.0,massa,ton/ano,65.00,0
3,1.904000e+09,2018.0,massa,ton/ano,200.00,0
4,1.904000e+09,2020.0,massa,ton/ano,200.00,0

In [27]:
df_cadri_final_agg.to_csv('../../data/final_cadri.csv', index=False)